const wordArray = [
    'the', 'be', 'to', 'of', 'and', 'a', 'in', 'that', 'have', 'it',
    'for', 'not', 'on', 'with', 'he', 'as', 'you', 'do', 'at', 'this',
    'but', 'his', 'by', 'from', 'they', 'we', 'say', 'her', 'she', 'or',
    'an', 'will', 'my', 'one', 'all', 'would', 'there', 'their', 'what',
    'so', 'up', 'out', 'if', 'about', 'who', 'get', 'which', 'go', 'me',
    'when', 'make', 'can', 'like', 'time', 'no', 'just', 'him', 'know',
    'take', 'people', 'into', 'year', 'your', 'good', 'some', 'could',
    'them', 'see', 'other', 'than', 'then', 'now', 'look', 'only', 'come',
    'its', 'over', 'think', 'also', 'back', 'after', 'use', 'two', 'how',
    'our', 'work', 'first', 'well', 'way', 'even', 'new', 'want', 'because',
    'any', 'these', 'give', 'day', 'most', 'us', 'food', 'dog', 'cat', 'car',
    'house', 'man', 'woman', 'child', 'money', 'job', 'friend', 'time',
    'way', 'life', 'world', 'hand', 'work', 'week', 'point', 'problem',
    'government', 'company', 'number', 'group', 'thing', 'woman', 'place',
    'day', 'year', 'family', 'fact', 'government', 'school', 'fact', 'home',
    'water', 'room', 'area', 'money', 'story', 'fact', 'month', 'lot', 'right',
    'study', 'book', 'eye', 'job', 'word', 'business', 'issue', 'side', 'kind',
    'head', 'house', 'service', 'friend', 'father', 'power', 'hour', 'game',
    'line', 'end', 'member', 'law', 'car', 'city', 'community', 'name', 'president',
    'team', 'minute', 'idea', 'kid', 'body', 'information', 'back', 'parent', 'face',
    'others', 'level', 'office', 'door', 'health', 'person', 'art', 'war', 'history',
    'party', 'result', 'change', 'morning', 'reason', 'research', 'girl', 'guy', 'moment',
    'air', 'teacher', 'force', 'education', 'pain', 'time', 'money', 'decision', 'event',
    'market', 'secret', 'team', 'future', 'company', 'road', 'church', 'material', 'career',
    'party', 'trade', 'history', 'future', 'story', 'conference', 'phone', 'resource', 'example',
    'country', 'life', 'problem', 'issue', 'case', 'child', 'system', 'level', 'group',
    'company', 'area', 'world', 'phone', 'fact', 'family', 'point', 'child', 'state',
    'week', 'activity', 'order', 'development', 'line', 'end', 'fact', 'business', 'research'
];